export { BaseRepository } from './base.repository';
export { TeacherRepository, teacherRepository } from './teacher.repository';
export { EmployeeRepository, employeeRepository } from './employee.repository';
export { StudentRepository, studentRepository } from './student.repository';
export { DashboardRepository, dashboardRepository } from './dashboard.repository';
export { ProductRepository, productRepository } from './product.repository';
export { CourseRepository, courseRepository } from './course.repository';
export { CourseTimeTableRepository, courseTimeTableRepository } from './coursetimetable.repository';
export { HandbookRepository, handbookRepository } from './handbook.repository';
export { FeedbackRepository, feedbackRepository } from './feedback.repository';
export { TeacherAttendanceLogRepository, teacherAttendanceLogRepository } from './teacherattendancelog.repository';
export { getRefOptions, ensureReftbl } from './reftbl.repository';
